### ISSUE TITLE
VersionParser->normalize() throws exception on valid version

### ISSUE THREAD

**Issue by jeabakker** [composer/semver#157]
when normalizing version `8.3.3-1+0~20240216.17+debian11~1.gbp87e37b` the VersionParser->normalize() throws an `UnexpectedValueException`.

If I'm reading the Semver specs correctly https://semver.org/#spec-item-9 this should be allowed

I believe the solution can be made in https://github.com/composer/semver/blob/1d09200268e7d1052ded8e5da9c73c96a63d18f5/src/VersionParser.php#L39
 by changing 
```php
private static $modifierRegex = '[._-]?(?:(stable|beta|b|RC|alpha|a|patch|pl|p)((?:[.-]?\d+)*+)?)?([.-]?dev)?'
```
to 
```php
private static $modifierRegex = '[._-]?(?:(stable|beta|b|RC|alpha|a|patch|pl|p)?((?:[.-]?\d+)*+)?)?([.-]?dev)?'
```

note the `?` after `(?:(stable|beta|b|RC|alpha|a|patch|pl|p)`

**Comment by naderman** [comment]
I think the short answer to this is that Composer doesn't support that part of semver. Prerelease versions in Composer are denoted with stability flags like beta/alpha, we don't support using a dash to indicate this.

**Comment by Seldaek** [comment]
Yeah we do not currently support these and I'd rather not tbh, also because adding support for such versions means old clients would break if anyone uses them.

That's why we parse the PHP version a bit differently with a fallback in case the version contains linux distro niceties in there. See https://github.com/composer/composer/blob/5a20dba768d489496446b0db4987a957af7e1d1b/src/Composer/Repository/PlatformRepository.php#L146-L152

You could also initialize a platform repo and use that to get the PHP version in your plugin, or use PHP_VERSION_MINOR/PHP_VERSION_MAJOR/.. to build a version string that is the pure x.y.z version.
