### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by alcohol** [composer/semver#4]
Needs documentation. Considering this library is a wee bit larger than [composer/spdx-licenses](/composer/spdx-licenses), I reckon it deserves proper documentation. E.g. not just some basic usage description in the README. Any suggestions / feedback?

**Comment by legoktm** [comment]
I think work on #2 will introduce documentation on the high-level functions that users should be using.

**Comment by alcohol** [comment]
/cc @Seldaek @stof @naderman 

How should we document components that get extracted? 

- Do we want to keep docs centralised in [composer/composer](/composer/composer) in `docs/`?
- Do we want to limit it to basic API docs such as for example generated by phpdocumentor? 
- Do we want it to be more user friendly, like readthedocs.org (which requires more manual writing)?

**Comment by Seldaek** [comment]
IMO composer docs should document composer-level features, and the docs 
here should just document the user friendly API (readthedocs or just 
github markdown) + maybe point to composer docs for the version 
constraints and stuff so we don't duplicate that.

**Comment by stof** [comment]
I agree with @Seldaek here.

Regarding the API doc, I'm not sure it is worth it. I don't want to have it committed in the repo (this is a pain, because it would mean than anyone doing a change should regenerate it so that the API doc in a commit corresponds to the code in this commit), and I don't know any tool providing phpdocumentor as a service, to build the API doc automatically on push and to host it.
Thus, an API doc alone is generally not what people want first. And they can look at the phpdoc of classes (or generate an API doc locally to browse it) if they really want. What we need is some doc explaining how to use the library. I'm not sure we need to use rST and readthedocs though. A few markdown files displayed by Github might be enough for what we need here.

**Comment by alcohol** [comment]
We could just use the Github wiki pages on this repository in that case. Or would you prefer to have some markdown files in a `doc/` folder for example?

**Comment by stof** [comment]
having a doc folder is better IMO:

- it allows to have a different doc per version (as the doc is versionned with the code)
- it allows to make doc changes go through the usual process to be reviewed
- it allows to have doc changes in the same PR than code changes, ensuring that we don't forget to update the doc.

I generally don't find github wikis to be well suited for documentation (they are great for other purposes, for instance maintaining a list of community resources about the library, as done in Silex for the third-party providers).

**Comment by alcohol** [comment]
Sounds good to me. I think that's settled then. Now someone just needs to get started on it ;-)
