### ISSUE TITLE
Question re: constraint logic syntax

### ISSUE THREAD

**Issue by okdana** [composer/semver#47]
Hey there, i have a question about the constraint logic syntax supported by this package:

Why is `||` supported for logical `OR`, but `&&` is not supported for logical `AND`?

I mean, it's [documented](https://getcomposer.org/doc/articles/versions.md#range) to work that way, so it's not a bug or anything, but i'm curious. Having been exposed to the `||` syntax independently, i just assumed that `&&` would also work.

Thanks!

**Comment by alcohol** [comment]
@Seldaek is there any specific reason?

Personally, I do not know. It was like this ever since I got on board. My guess would be that since the AND is already implicit by default, there was no need or desire to make it explicit?

Writing `>1.2 <1.6` is just as clear as `>1.2 && <1.6`. By supporting the latter (`&&` notation), thinks would just become more ambiguous. What would be the meaning of `>1.2 <1.6` for example? Is it now implicitly `&&` or `||`?

**Comment by Seldaek** [comment]
We initially only supported A,B for AND and A|B for OR, then added support for the space and || to be compatible with npm notations. Adding more just adds confusion IMO.

**Comment by okdana** [comment]
Fair. Thanks for explaining!
