### ISSUE TITLE
Stability constraints

### ISSUE THREAD

**Issue by theofidry** [composer/semver#49]
If I have the following list of available versions:

```php
$availableVersions = [
    '2.0.0',
    'dev-master',
    '1.x-dev',
    '1.0.0',
    '1.0.0-RC2',
    '1.0.0-RC1',
    '1.0.0-RC',
    '1.0.0-beta2',
    '1.0.0-beta1',
    '1.0.0-beta',
    '1.0.0-alpha2',
    '1.0.0-alpha1',
    '1.0.0-alpha',
]
```

Then:

```php
$constraint = '^1.0';

$versions = [];
foreach ($availableVersions as $availableVersion) {
    if (Semver::satisfies($availableVersion, constraint)) {
        $versions[] = $availableVersion;
    }
}
```

I would expect the result to be:

```php
$versions = [
    '1.0.0',
]
```

Likewise, I would expect for `$version = ^1.0@beta` to give me:

```php
$versions = [
    '1.0.0',
    '1.0.0-RC2',
    '1.0.0-RC1',
    '1.0.0-RC',
    '1.0.0-beta2',
    '1.0.0-beta1',
    '1.0.0-beta',
]

Yet in both cases I'm getting:

```php
$versions = [
    'dev-master',
    '1.x-dev',
    '1.0.0',
    '1.0.0-RC2',
    '1.0.0-RC1',
    '1.0.0-RC',
    '1.0.0-beta2',
    '1.0.0-beta1',
    '1.0.0-beta',
    '1.0.0-alpha2',
    '1.0.0-alpha1',
    '1.0.0-alpha',
]
```

Looking [at the code](https://github.com/composer/semver/blob/master/src/VersionParser.php#L382), I can see that for the caret at least, the default stability is `dev` whilst I would expect `stable` instead. Is there any way to change that or I am missing something?

**Comment by Seldaek** [comment]
The issue is by default it uses -dev if you don't specify the stability, and the other issue is that the `@<stability>` notation is composer specific and not supported here.

If you use `^1.0-beta` or `^1.0-stable` you will get what you want, except for 1.x-dev always being returned as it is higher than 1.0.. If you want to filter versions that are less than a given stability you would need a second pass and some manual work with VersionParser::parseStability to filter out the versions that are below a given stability level.

**Comment by theofidry** [comment]
Ok, thanks for the clarifications
