### ISSUE TITLE
unable to verify signed git tag

### ISSUE THREAD

**Issue by DavidPrevot** [composer/semver#67]
Hi,

The last tag (1.5.0) seems to be signed, thanks. Unfortunately, the format looks weird, and cannot be verified (`git tag -v 1.5.0` fails).

Regards

**Comment by alcohol** [comment]
I think it's because it's both a tag and a commit. I could be wrong though.

```
$ git tag -v 1.5.0
error: 1.5.0: cannot verify a non-tag object of type commit.
```

**Comment by alcohol** [comment]
https://git-scm.com/book/fi/v1/Gitin-perusteet-Tagging#Signed-Tags

The example here shows that `git show <tag>` should include the gpg key in the output. This does not seem to be the case for this tag when I look at it though. Not sure why. Github does recognize it as a signed tag somehow.

Also, for git, you need the signers key in your local keyring. See https://git-scm.com/book/fi/v1/Gitin-perusteet-Tagging#Verifying-Tags

**Comment by alcohol** [comment]
@Seldaek any idea what you did here?

**Comment by Seldaek** [comment]
I have in my git config: commit.gpgsign=true and user.signingkey=C4359456C83878B3 (which you can find at https://keybase.io/seldaek)

$ git verify-commit 1.5.0
gpg: Signature made Tue 19 Mar 2019 06:25:45 PM STD
gpg:                using RSA key 12CE50EA6FC390E6E733458A7BBD42C429EC80BC
gpg: Good signature from "Jordi Boggiano <j.boggiano@seld.be>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 96DC 30A1 E352 6046 F9A1  31E9 C435 9456 C838 78B3 (here is the pub key last 4 blocks)
     Subkey fingerprint: 12CE 50EA 6FC3 90E6 E733  458A 7BBD 42C4 29EC 80BC

I guess for git tag -v to work, I'd have to create annotated tags which creates a new git object for the tag instead of referencing an existing commit.. I won't commit to do this in the future because tbh I'll probably forget.

**Comment by alcohol** [comment]
> I guess for git tag -v to work, I'd have to create annotated tags which creates a new git object for the tag instead of referencing an existing commit.. 

I think that is indeed the case.

**Comment by stof** [comment]
@Seldaek or you could configure `tag.forceSignAnnotated` in your git config

**Comment by stof** [comment]
hmm, no. this forces annotated tags to be signed (even if `-s` was not used), but it does not look like it would force tags to be always annotated

**Comment by DavidPrevot** [comment]
Hi,

> user.signingkey=C4359456C83878B3 (which you can find at https://keybase.io/seldaek)

Please, push it also to the keyserver network in order to make it available (and get it signed).

> git verify-commit

Nice! I missed that the other commits were signed too (I only noticed it via an unusual display of the signature for the 1.5.0 tag with gitk). Thank you.
